gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of organisms!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call an “organism.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as organisms.\p"
	.string "We humans live alongside organisms, at\n"
	.string "times as friendly playmates, and at\l"
	.string "times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about organisms.\p"
	.string "In fact, there are many, many secrets\n"
	.string "surrounding organisms.\p"
	.string "To unravel nature mysteries, I've been\n"
	.string "undertaking research. That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LADNER.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the world of\n"
	.string "organisms where dreams, adventure, and\l"
	.string "friendships await!\p"
	.string "Well, I'll be expecting you later. Come\n"
	.string "see me in my FIELD LAB.\p"
	.string "$"
