gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the wild side of BC!\p"
	.string "My name is MACOUN.\p"
	.string "But everyone calls me the PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This masked visitor is what we\n"
	.string "call an “organism.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "From the mudflats of the delta to the\n"
	.string "peaks of the Coast Mountains, this land\l"
	.string "is alive with organisms.\p"
	.string "Mammals and birds, insects and fungi,\n"
	.string "kelp, slugs… even microbes too small\l"
	.string "to see.\p"
	.string "Some people team up with them as\n"
	.string "partners, and test their skills\l"
	.string "against other TRAINERS.\p"
	.string "But for all our time together, we\n"
	.string "still know so little about them.\p"
	.string "Every rain-soaked forest and tide pool\n"
	.string "holds secrets nobody has written down.\p"
	.string "Recording them in a FIELD JOURNAL…\n"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LADNER.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own field season is about\n"
	.string "to begin.\p"
	.string "Grab your boots and step out into a\n"
	.string "world of organisms, where discovery,\l"
	.string "adventure, and friendship await!\p"
	.string "Well, I'll be expecting you later. Come\n"
	.string "see me in my FIELD LAB.\p"
	.string "$"
