gText_WouldYouLikeToRestYourPkmn::
	.string "Hello, and welcome to the FIELD\n"
	.string "STATION.\p"
	.string "We restore your tired organisms to full\n"
	.string "health.\p"
	.string "Would you like to rest your partners?$"

gText_IllTakeYourPkmn::
	.string "Okay, I'll take your partners for a few\n"
	.string "seconds.$"

gText_RestoredPkmnToFullHealth::
	.string "Thank you for waiting.\p"
	.string "We've restored your partners to full\n"
	.string "health.$"

gText_WeHopeToSeeYouAgain::
	.string "We hope to see you again!$"

gText_WelcomeCutShort::
	.string "Hello, and welcome to the FIELD\n"
	.string "STATION.\p"
	.string "We restore your tired organisms to full\n"
	.string "health.\p"
	.string "Would you like to…$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me the\n"
	.string "honor of resting your partners!$"

gText_YouWantTheUsual::
	.string "I'm delighted to see you, {PLAYER}!\n"
	.string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
	.string "Okay, I'll take your partners for a few\n"
	.string "seconds.$"

gText_ThankYouForWaiting::
	.string "Thank you for waiting.$"

gText_WeHopeToSeeYouAgain2::
	.string "We hope to see you again!$"
