gBirchDexRatingText_AreYouCurious::
	.string "PROF. MACOUN: Ah, {PLAYER}{KUN}!\p"
	.string "Are you curious about how your FIELD\n"
	.string "JOURNAL is coming along?$"

gBirchDexRatingText_Cancel::
	.string "Hm? Oh, you haven't caught enough\n"
	.string "organisms to make it worthwhile.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "So, you've seen {STR_VAR_1} organisms,\n"
	.string "and you've caught {STR_VAR_2}\l"
	.string "organisms…$"

gBirchDexRatingText_LessThan10::
	.string "Go into grassy areas more and look for\n"
	.string "organisms more carefully.$"

gBirchDexRatingText_LessThan20::
	.string "I guess you're getting the hang\n"
	.string "of it. But, it gets harder from here.$"

gBirchDexRatingText_LessThan30::
	.string "Some organisms only appear in certain\n"
	.string "areas. You must be persistent.$"

gBirchDexRatingText_LessThan40::
	.string "Well, it could use more quantity, but\n"
	.string "this is looking more like a FIELD\l"
	.string "JOURNAL now.$"

gBirchDexRatingText_LessThan50::
	.string "This is coming along pretty good.\n"
	.string "Keep up the effort.$"

gBirchDexRatingText_LessThan60::
	.string "Are you using any RODS? There are many\n"
	.string "organisms in the sea.$"

gBirchDexRatingText_LessThan70::
	.string "Instead of just catching organisms,\n"
	.string "how about making them evolve, too?$"

gBirchDexRatingText_LessThan80::
	.string "This is going to be a fantastic FIELD\n"
	.string "JOURNAL. That's the feeling I'm\l"
	.string "getting.$"

gBirchDexRatingText_LessThan90::
	.string "You've collected this many…\n"
	.string "Your talent is remarkable!$"

gBirchDexRatingText_LessThan100::
	.string "Have you visited the BURNS BOG?\p"
	.string "I hear there are some organisms that\n"
	.string "can only be caught there.$"

gBirchDexRatingText_LessThan110::
	.string "You've finally reached\n"
	.string "the 100-kind mark.\p"
	.string "This is an impressive FIELD JOURNAL!$"

gBirchDexRatingText_LessThan120::
	.string "There might be organisms that can be\n"
	.string "found using ROCK SMASH.$"

gBirchDexRatingText_LessThan130::
	.string "You should get some more organisms by\n"
	.string "trading with others.$"

gBirchDexRatingText_LessThan140::
	.string "I've heard of organisms that evolve\n"
	.string "when they come to fully love their\l"
	.string "TRAINERS.$"

gBirchDexRatingText_LessThan150::
	.string "I had no idea that there were so many\n"
	.string "nature species in BC.$"

gBirchDexRatingText_LessThan160::
	.string "On occasion, some organisms appear in\n"
	.string "large numbers like outbreaks.\p"
	.string "Don't miss opportunities like\n"
	.string "those.$"

gBirchDexRatingText_LessThan170::
	.string "One can get a very good idea about the\n"
	.string "organism of BC by\l"
	.string "looking through your FIELD JOURNAL.$"

gBirchDexRatingText_LessThan180::
	.string "I would say you already qualify as a\n"
	.string "PROFESSOR, and a good one, too!$"

gBirchDexRatingText_LessThan190::
	.string "With a FIELD JOURNAL this complete,\n"
	.string "you're a real professional at this!$"

gBirchDexRatingText_LessThan200::
	.string "You're very close to completing this\n"
	.string "FIELD JOURNAL. I can feel it in my\l"
	.string "bones!$"

gBirchDexRatingText_DexCompleted::
	.string "Congratulations! Your FIELD JOURNAL is\n"
	.string "complete!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm…\n"
	.string "On a nationwide basis…\p"
	.string "You've seen {STR_VAR_1} organisms, and\n"
	.string "you've caught {STR_VAR_2} organisms…$"
