gTrickHouse_Mechadoll_Oddish::
	.string "BANANASLUG$"

gTrickHouse_Mechadoll_Poochyena::
	.string "GHOST PIPE$"

gTrickHouse_Mechadoll_Taillow::
	.string "BROWNBAT$"

gTrickHouse_Mechadoll_Azurill::
	.string "POLYP$"

gTrickHouse_Mechadoll_Lotad::
	.string "ALEVIN$"

gTrickHouse_Mechadoll_Wingull::
	.string "TADPOLE$"

gTrickHouse_Mechadoll_Dustox::
	.string "SWALLOWTAL$"

gTrickHouse_Mechadoll_Zubat::
	.string "SAGEBRUSH$"

gTrickHouse_Mechadoll_Nincada::
	.string "NYMPH$"

gTrickHouse_Mechadoll_Ralts::
	.string "SAR11$"

gTrickHouse_Mechadoll_Zigzagoon::
	.string "KINGFISHER$"

gTrickHouse_Mechadoll_Slakoth::
	.string "HERRING$"

gTrickHouse_Mechadoll_Poochyena2::
	.string "GHOST PIPE$"

gTrickHouse_Mechadoll_Shroomish::
	.string "FLY AGARIC$"

gTrickHouse_Mechadoll_Zigzagoon2::
	.string "CROW$"

gTrickHouse_Mechadoll_Poochyena3::
	.string "GHOST PIPE$"

gTrickHouse_Mechadoll_Zubat2::
	.string "SAGEBRUSH$"

gTrickHouse_Mechadoll_Carvanha::
	.string "MEGALOPA$"

gTrickHouse_Mechadoll_BurnHeal::
	.string "BURN HEAL$"

gTrickHouse_Mechadoll_HarborMail::
	.string "HARBOR MAIL$"

gTrickHouse_Mechadoll_SamePrice::
	.string "Same price$"

gTrickHouse_Mechadoll_60Yen::
	.string "¥60$"

gTrickHouse_Mechadoll_55Yen::
	.string "¥55$"

gTrickHouse_Mechadoll_Nothing::
	.string "Nothing$"

gTrickHouse_Mechadoll_CostMore::
	.string "They will cost more.$"

gTrickHouse_Mechadoll_CostLess::
	.string "They will cost less.$"

gTrickHouse_Mechadoll_SamePrice2::
	.string "Same price$"

gTrickHouse_Mechadoll_Male::
	.string "Male$"

gTrickHouse_Mechadoll_Female::
	.string "Female$"

gTrickHouse_Mechadoll_Neither::
	.string "Neither$"

gTrickHouse_Mechadoll_ElderlyMen::
	.string "Elderly men$"

gTrickHouse_Mechadoll_ElderlyLadies::
	.string "Elderly ladies$"

gTrickHouse_Mechadoll_SameNumber::
	.string "Same number$"

gTrickHouse_Mechadoll_None::
	.string "None$"

gTrickHouse_Mechadoll_One::
	.string "1$"

gTrickHouse_Mechadoll_Two::
	.string "2$"

gTrickHouse_Mechadoll_Two2::
	.string "2$"

gTrickHouse_Mechadoll_Three::
	.string "3$"

gTrickHouse_Mechadoll_Four::
	.string "4$"

gTrickHouse_Mechadoll_Six::
	.string "6$"

gTrickHouse_Mechadoll_Seven::
	.string "7$"

gTrickHouse_Mechadoll_Eight::
	.string "8$"

gTrickHouse_Mechadoll_Six2::
	.string "6$"

gTrickHouse_Mechadoll_Seven2::
	.string "7$"

gTrickHouse_Mechadoll_Eight2::
	.string "8$"
