SootopolisCity_House7_MapScripts::
	.byte 0

SootopolisCity_House7_EventScript_OldMan::
	msgbox SootopolisCity_House7_Text_CityFromEruptedVolcano, MSGBOX_NPC
	end

SootopolisCity_House7_EventScript_PokefanF::
	msgbox SootopolisCity_House7_Text_CaveMadeToKeepSomething, MSGBOX_NPC
	end

SootopolisCity_House7_Text_CityFromEruptedVolcano:
	.string "Long ago, glaciers carved this inlet\n"
	.string "deep into the mountains.\p"
	.string "When the ice melted, the sea flowed in\n"
	.string "and filled the cove.\p"
	.string "That's how DEEP COVE came into\n"
	.string "being.$"

SootopolisCity_House7_Text_CaveMadeToKeepSomething:
	.string "The cave that links DEEP COVE and\n"
	.string "the outside world…\p"
	.string "It seems as if the cave was made to\n"
	.string "keep something from getting out.\p"
	.string "Or am I just imagining things?$"

