OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "When a battle starts, the one at the\n"
	.string "left of the list goes out first.\p"
	.string "So, when you get more organisms in your\n"
	.string "party, try switching around the order\l"
	.string "of your partners.\p"
	.string "It could give you an advantage.$"

