#define EGG_MOVES_SPECIES_OFFSET 20000
#define EGG_MOVES_TERMINATOR 0xFFFF
#define egg_moves(species, moves...) (SPECIES_##species + EGG_MOVES_SPECIES_OFFSET), moves

// Generated by atlas/apply_species.js. Living Atlas organisms have no egg moves.
const u16 gEggMoves[] = {
    EGG_MOVES_TERMINATOR
};
