#!/usr/bin/env python3
"""Living Atlas types: names, type chart, Ghost/Dragon move retyping and type icons.

Run from the repo root: python3 atlas/apply_types.py (idempotent).
"""
import json
import os
import re

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
P = lambda *a: os.path.join(ROOT, *a)

LA_TO_GEN3 = {
    'Common': 'NORMAL', 'Brawn': 'FIGHTING', 'Sky': 'FLYING', 'Toxin': 'POISON', 'Soil': 'GROUND',
    'Stone': 'ROCK', 'Chitin': 'BUG', 'Armor': 'STEEL', 'Ember': 'FIRE', 'Aqua': 'WATER',
    'Verdant': 'GRASS', 'Charm': 'ELECTRIC', 'Mind': 'PSYCHIC', 'Frost': 'ICE', 'Night': 'DARK',
}
# Retired types keep a slot but nothing uses them.
NAMES = {v: k.upper() for k, v in LA_TO_GEN3.items()}
NAMES.update({'GHOST': '-----', 'DRAGON': '-----', 'MYSTERY': '???'})
ICON_FILES = {
    'NORMAL': 'normal', 'FIGHTING': 'fight', 'FLYING': 'flying', 'POISON': 'poison', 'GROUND': 'ground', 'ROCK': 'rock',
    'BUG': 'bug', 'GHOST': 'ghost', 'STEEL': 'steel', 'MYSTERY': 'mystery', 'FIRE': 'fire', 'WATER': 'water',
    'GRASS': 'grass', 'ELECTRIC': 'electric', 'PSYCHIC': 'psychic', 'ICE': 'ice', 'DRAGON': 'dragon', 'DARK': 'dark',
}
RETYPE = {
    'LICK': 'DARK', 'ASTONISH': 'DARK', 'NIGHT_SHADE': 'DARK', 'SHADOW_PUNCH': 'DARK', 'SHADOW_BALL': 'DARK',
    'CONFUSE_RAY': 'DARK', 'DESTINY_BOND': 'DARK', 'GRUDGE': 'DARK', 'SPITE': 'DARK', 'NIGHTMARE': 'DARK',
    'DRAGON_RAGE': 'FIGHTING', 'TWISTER': 'FLYING', 'DRAGON_BREATH': 'FIRE', 'DRAGON_CLAW': 'FIGHTING',
    'OUTRAGE': 'FIGHTING', 'DRAGON_DANCE': 'FIGHTING',
}


def read(p):
    with open(P(p), encoding='utf-8') as f:
        return f.read()


def write(p, s):
    with open(P(p), 'w', encoding='utf-8') as f:
        f.write(s)


def atlas_types():
    with open(P('atlas', 'data', 'types.json'), encoding='utf-8') as f:
        return json.load(f)


# ---- names
src = read('src/battle_main.c')
for t, name in NAMES.items():
    src = re.sub(r'(\[TYPE_%s\] = _\(")[^"]*("\))' % t, r'\g<1>%s\g<2>' % name, src)

# ---- type chart: Living Atlas chart, entries other than 1x.
chart = atlas_types()['chart']
MUL = {2: 'TYPE_MUL_SUPER_EFFECTIVE', 0.5: 'TYPE_MUL_NOT_EFFECTIVE', 0: 'TYPE_MUL_NO_EFFECT'}
rows = []
for atk, row in chart.items():
    for dfn, m in row.items():
        if m != 1:
            rows.append('    TYPE_%s, TYPE_%s, %s,' % (LA_TO_GEN3[atk], LA_TO_GEN3[dfn], MUL[m]))
rows.append('    TYPE_FORESIGHT, TYPE_FORESIGHT, TYPE_MUL_NO_EFFECT,')
rows.append('    TYPE_ENDTABLE, TYPE_ENDTABLE, TYPE_MUL_NO_EFFECT')
table = ('// Living Atlas type chart, generated by atlas/apply_types.py.\n'
         'const u8 gTypeEffectiveness[%d] =\n{\n%s\n};' % (len(rows) * 3, '\n'.join(rows)))
src = re.sub(r'(// Living Atlas type chart[^\n]*\n)?const u8 gTypeEffectiveness\[\d+\] =\n\{[\s\S]*?\n\};', lambda m: table, src)
write('src/battle_main.c', src)

# Type names up to 7 letters (VERDANT).
g = read('include/constants/global.h')
write('include/constants/global.h', re.sub(r'#define TYPE_NAME_LENGTH \d+', '#define TYPE_NAME_LENGTH 7', g))

# ---- retype Ghost and Dragon moves
mv = read('src/data/battle_moves.h')
for move, t in RETYPE.items():
    mv = re.sub(r'(\[MOVE_%s\] =\s*\{[\s\S]*?\.type = )TYPE_\w+' % move, r'\g<1>TYPE_%s' % t, mv, count=1)
write('src/data/battle_moves.h', mv)

# ---- type icons: erase the old label and draw the new one with a 3x7 pixel font.
FONT = {
    'A': ['.#.', '#.#', '#.#', '###', '#.#', '#.#', '#.#'], 'B': ['##.', '#.#', '#.#', '##.', '#.#', '#.#', '##.'],
    'C': ['.##', '#..', '#..', '#..', '#..', '#..', '.##'], 'D': ['##.', '#.#', '#.#', '#.#', '#.#', '#.#', '##.'],
    'E': ['###', '#..', '#..', '##.', '#..', '#..', '###'], 'F': ['###', '#..', '#..', '##.', '#..', '#..', '#..'],
    'G': ['.##', '#..', '#..', '#.#', '#.#', '#.#', '.##'], 'H': ['#.#', '#.#', '#.#', '###', '#.#', '#.#', '#.#'],
    'I': ['###', '.#.', '.#.', '.#.', '.#.', '.#.', '###'], 'K': ['#.#', '#.#', '##.', '#..', '##.', '#.#', '#.#'],
    'L': ['#..', '#..', '#..', '#..', '#..', '#..', '###'], 'M': ['#...#', '##.##', '#.#.#', '#.#.#', '#...#', '#...#', '#...#'],
    'N': ['#..#', '##.#', '##.#', '#.##', '#.##', '#..#', '#..#'], 'O': ['.#.', '#.#', '#.#', '#.#', '#.#', '#.#', '.#.'],
    'Q': ['.#.', '#.#', '#.#', '#.#', '#.#', '##.', '.##'], 'R': ['##.', '#.#', '#.#', '##.', '#.#', '#.#', '#.#'],
    'S': ['.##', '#..', '#..', '.#.', '..#', '..#', '##.'], 'T': ['###', '.#.', '.#.', '.#.', '.#.', '.#.', '.#.'],
    'U': ['#.#', '#.#', '#.#', '#.#', '#.#', '#.#', '###'], 'V': ['#.#', '#.#', '#.#', '#.#', '#.#', '#.#', '.#.'],
    'W': ['#...#', '#...#', '#...#', '#.#.#', '#.#.#', '##.##', '#...#'], 'X': ['#.#', '#.#', '#.#', '.#.', '#.#', '#.#', '#.#'],
    'Y': ['#.#', '#.#', '#.#', '.#.', '.#.', '.#.', '.#.'], '?': ['##.', '..#', '..#', '.#.', '.#.', '...', '.#.'],
    '-': ['...', '...', '...', '###', '...', '...', '...'],
}


def draw_label(path, text):
    im = Image.open(path)
    px = im.load()
    w, h = im.size
    bg = px[1, 3]
    for y in range(4, 12):
        for x in range(1, w - 1):
            px[x, y] = bg
    widths = [len(FONT[c][0]) for c in text]
    gap = 2 if sum(widths) + 2 * (len(text) - 1) <= w - 4 else 1
    total = sum(widths) + gap * (len(text) - 1)
    x0 = max(1, (w - total) // 2)
    glyph = set()
    x = x0
    for c, cw in zip(text, widths):
        for gy, row in enumerate(FONT[c]):
            for gx, ch in enumerate(row):
                if ch == '#':
                    glyph.add((x + gx, 4 + gy))
        x += cw + gap
    for (gx, gy) in glyph:
        for sx, sy in ((gx + 1, gy), (gx, gy + 1), (gx + 1, gy + 1)):
            if (sx, sy) not in glyph and 1 <= sx < w - 1 and sy <= 11:
                px[sx, sy] = 0xe
    for (gx, gy) in glyph:
        if 1 <= gx < w - 1:
            px[gx, gy] = 0xf
    im.save(path)


for t, f in ICON_FILES.items():
    draw_label(P('graphics', 'types', f + '.png'), NAMES[t])

print('types: names, chart (%d entries), %d moves retyped, %d icons' % (len(rows) - 2, len(RETYPE), len(ICON_FILES)))

# Keep the header's array size in step with the generated table.
hdr = read('include/battle_main.h')
write('include/battle_main.h', re.sub(r'extern const u8 gTypeEffectiveness\[\d*\];',
                                      'extern const u8 gTypeEffectiveness[%d];' % (len(rows) * 3), hdr))
