#!/usr/bin/env node
// Writes docs/ROSTER.md: the 202-entry BC Field Journal in regional order, then the BC organisms
// in worldwide slots. Run after atlas/pick_species.js: node atlas/roster_doc.js
'use strict';
const C = require('./lib/common');

const map = C.readJSON('atlas/species_map.json');
const orgs = C.loadOrganisms();
const names = C.readJSON('atlas/names.json');
const bySlot = Object.fromEntries(map.map((e) => [e.slot, e]));
const bcNew = new Set(C.readJSON('atlas/bc_species.json').species.filter((s) => !s.override).map((s) => s.id));

const note = (o) => [
	o.legendary, o.invasive ? 'invasive' : null, o.fossil_site ? 'fossil' : null, o.line ? (o.stage ? `life stage: ${o.stage}` : 'life stage') : null,
	bcNew.has(o.id) ? 'new' : null,
].filter(Boolean).join(', ');
const habitats = (o) => (o.bc_habitats || []).join(', ');
const row = (n, slot) => {
	const o = orgs[bySlot[slot].id];
	return `| ${n} | ${C.gameName(o, names)} | ${o.name} | ${o.types.join(' / ')} | ${o.bst} | ${habitats(o)} | ${note(o)} | ${slot} |`;
};

const regional = C.hoennOrder();
let md = '# Field Journal roster\n\nGenerated by `node atlas/roster_doc.js` from `atlas/species_map.json`. ' +
	'"new" marks organisms added in `atlas/bc_species.json`; the rest come from the Living Atlas database.\n\n' +
	`## BC Field Journal (${regional.length})\n\n| # | In game | Organism | Types | Total | BC habitats | Notes | Slot |\n|---|---|---|---|---|---|---|---|\n`;
regional.forEach((slot, i) => { md += row(i + 1, slot) + '\n'; });

const extra = map.filter((e) => !regional.includes(e.slot) && (bcNew.has(e.id) || orgs[e.id].region === 'bc'));
md += `\n## BC organisms outside the regional Journal (${extra.length})\n\n| # | In game | Organism | Types | Total | BC habitats | Notes | Slot |\n|---|---|---|---|---|---|---|---|\n`;
for (const e of extra) md += row(e.dex, e.slot) + '\n';
md += `\nThe other ${map.length - regional.length - extra.length} national slots hold worldwide Living Atlas organisms, met after the credits.\n`;
C.write('docs/ROSTER.md', md);
console.log('roster_doc: docs/ROSTER.md written');
